version: '3'

vars:
  IMAGE_NAME: realgan
  IMAGE_TAG: latest
  CONTAINER_NAME: realgan

tasks:
  setup:
    cmds:
      - sudo dnf install -y podman podman-compose podman-docker
      - mkdir -p input output
      - sudo dnf install -y audit
      - echo "Checking audit rules..."
      - |
        if ! sudo auditctl -l | grep -q "/usr/bin/podman"; then
          sudo auditctl -w /usr/bin/podman -k podman-audit
        fi

  build:
    cmds:
      - podman build --security-opt seccomp=seccomp-profile.json --security-opt label=type:container_t -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} .

  scan:
    cmds:
      - dnf install -y trivy
      - trivy image {{.IMAGE_NAME}}:{{.IMAGE_TAG}}

  run:
    cmds:
      - |
        podman run --rm \
          --name {{.CONTAINER_NAME}} \
          --security-opt seccomp=profile.json \
          --security-opt label=type:container_t \
          --read-only \
          --device nvidia.com/gpu=all \
          --volume ./input:/home/realgan/input:ro \
          --volume ./output:/home/realgan/output:rw \
          {{.IMAGE_NAME}}:{{.IMAGE_TAG}}

  monitor:
    cmds:
      - podman stats {{.CONTAINER_NAME}}
      - nvidia-smi

  logs:
    cmds:
      - podman logs --follow {{.CONTAINER_NAME}}

  audit:
    cmds:
      - sudo ausearch -k podman-audit

  gpu-test:
    cmds:
      - |
        podman run --rm \
          --device nvidia.com/gpu=all \
          nvidia/cuda:11.8.0-base-ubuntu22.04 \
          nvidia-smi